package labs_examples.exception_handling.labs;

/**
 * Exception Handling Exercise 4:
 *
 *      Demonstrate a nested try/catch.
 *      try{
 *          // block of code to monitor for errors
 *        } catch (Exception e){
 *          // handle for Exception e
 *                  try {
 *                  // block of code - nested try
 *                   } catch {
 *                  // handle any exception that occur inside the nested try
 *                   }
 *          }
 *
 *
 */
